name: CI

on: [push]

jobs:
  typo3-12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.1, 8.0]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          command: require typo3/cms-core:^12
          args: --ignore-platform-reqs
          php_version: ${{ matrix.php }}
      - uses: php-actions/phpunit@v3
        with:
          version: 9.5
          php_version: ${{ matrix.php }}
